services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /opt/ead-ca2-deploy/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9092:9090"
    networks:
      - ca2-network
networks:
  ca2-network:
    driver: bridge
