version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - /opt/ead-ca2-deploy/monitoring/prometheus/alert-manager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - ca2-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /opt/ead-ca2-deploy/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/ead-ca2-deploy/monitoring/prometheus/alert-manager/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - "9092:9090"
    networks:
      - ca2-network
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - /opt/ead-ca2-deploy/monitoring/prometheus/blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - ca2-network
networks:
  ca2-network:
    driver: bridge
