services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - ca2-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
networks:
  ca2-network:
    driver: bridge
