services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - ca2-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
networks:
  ca2-network:
    driver: bridge
