services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /opt/ead-ca2-deploy/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9092:9090"
    networks:
      - ca2-network
  mongo-exporter:
    image: percona/mongodb_exporter:0.39
    container_name: mongo-exporter
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    networks:
      - ca2-network
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - ca2-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
networks:
  ca2-network:
    driver: bridge
