services:
  backend:
    container_name: backend-dev
    image: recipe-backend-dev:latest
    build: ../ead-ca2-BE
    ports:
      - "9090:9090"
    networks:
      - ca2-network-dev
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090"]
      interval: 10s
      timeout: 5s
      retries: 3
  frontend:
    container_name: frontend-dev
    image: recipe-frontend-dev:latest
    build: ../ead-ca2-FE
    ports:
      - "80:22137"
    networks:
      - ca2-network-dev
    depends_on:
      backend:
        condition: service_healthy
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - ca2-network-dev
networks:
  ca2-network-dev:
    driver: bridge
