services:
  backend:
    container_name: backend-dev
    image: recipe-backend-dev:latest
    build: ../ead-ca2-BE
    ports:
      - "9191:9191"
    networks:
      - ca2-network-dev
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9191"]
      interval: 10s
      timeout: 5s
      retries: 3
  frontend:
    container_name: frontend-dev
    image: recipe-frontend-dev:latest
    build: ../ead-ca2-FE
    ports:
      - "81:32137"
    networks:
      - ca2-network-dev
    depends_on:
      backend:
        condition: service_healthy
  mongo:
    image: mongo-dev
    ports:
      - "37017:37017"
    networks:
      - ca2-network-dev
networks:
  ca2-network:
    driver: bridge
