services:
  backend:
    image: recipe-backend:latest
    build: ../ead-ca2-BE
    ports:
      - "9090:9090"
    networks:
      - ca2-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: recipe-frontend:latest
    build: ../ead-ca2-FE
    ports:
      - "80:22137"
    networks:
      - ca2-network
    depends_on:
      backend:
        condition: service_healthy

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - ca2-network

networks:
  ca2-network:
    driver: bridge
