global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['188.166.18.67:22138', '167.172.45.92:22138']

  - job_name: 'backend'
    static_configs:
      - targets: ['188.166.18.67:8081', '167.172.45.92:8081']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['164.92.223.245:9216']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://188.166.18.67/health
          - http://167.172.45.92/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 64.225.83.15:9115
