global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend-blue:22138', 'frontend-green:22138']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend-blue:8081', 'backend-green:8081']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo-exporter:9216']

  - job_name: 'sidecar-health'
    static_configs:
      - targets: ['sidecar-blue:8080', 'sidecar-green:8080']
