global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['188.166.18.67:22138', '167.172.45.92:22138']

  - job_name: 'backend'
    static_configs:
      - targets: ['188.166.18.67:8081', '167.172.45.92:8081']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['164.92.223.245:9216']

  - job_name: 'sidecar-health'
    static_configs:
      - targets: ['188.166.18.67:8080', '167.172.45.92:8080']
