global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:9090']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:22138']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']