groups:
  - name: Frontend_Health
    rules:
      - alert: FrontendDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Frontend down on {{ $labels.instance }}"
          description: "Health check failed for {{ $labels.instance }}"
