groups:
  - name: blackbox
    rules:
      - alert: FrontendHealthDown
        expr: probe_success == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Frontend healthcheck failed"
          description: "The frontend at {{ $labels.instance }} is DOWN (blackbox failed)."
