groups:
  - name: BlackboxAlerts
    rules:
      - alert: FrontendHealthDown
        expr: probe_http_status_code == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Frontend healthcheck failed"
          description: "The frontend at {{ $labels.instance }} is down (blackbox probe failed)."
